OogZip : ZipExtractor.cs ZipExtractorFactory.cs EmptyExtractor.cs
	csc.exe /target:library /out:OogZip.dll /r:OogPlugin.dll /r:ICSharpCode.SharpZipLib.dll /res:Oog.Plugin.ZipExtractorFactory.resources ZipExtractor.cs ZipExtractorFactory.cs EmptyExtractor.cs
	copy OogZip.dll ..\..\